"""Adversarial Fault Injection Templates for 15 Prototype 3 Benchmark Scenarios."""

from enum import Enum


class ScenarioTemplate(str, Enum):
    S01_CLEAN_EXACT_MATCH = "S01_CLEAN_EXACT_MATCH"
    S02_FEE_ADJUSTED_MDR = "S02_FEE_ADJUSTED_MDR"
    S03_GST_DISCREPANCY = "S03_GST_DISCREPANCY"
    S04_SPLIT_PAYMENT = "S04_SPLIT_PAYMENT"
    S05_VALID_REVERSAL = "S05_VALID_REVERSAL"
    S06_EXPIRED_REVERSAL = "S06_EXPIRED_REVERSAL"
    S07_DUPLICATE_REVERSAL = "S07_DUPLICATE_REVERSAL"
    S08_MERCHANT_NAME_TYPO = "S08_MERCHANT_NAME_TYPO"
    S09_FX_ROUNDING = "S09_FX_ROUNDING"
    S10_UNEXPLAINED_MISMATCH = "S10_UNEXPLAINED_MISMATCH"
    S11_CARD_T2_SETTLEMENT = "S11_CARD_T2_SETTLEMENT"
    S12_HOLIDAY_SETTLEMENT = "S12_HOLIDAY_SETTLEMENT"
    S13_MISSING_APPROVAL_TOKEN = "S13_MISSING_APPROVAL_TOKEN"
    S14_CANDIDATE_TIE_AMBIGUITY = "S14_CANDIDATE_TIE_AMBIGUITY"
    S15_REPEATED_MICRO_CREDIT_LEAKAGE = "S15_REPEATED_MICRO_CREDIT_LEAKAGE"

    # Backward compatibility aliases
    CLEAN_MATCH = "S01_CLEAN_EXACT_MATCH"
    FEE_TAX_VARIANCE = "S02_FEE_ADJUSTED_MDR"
    DELAYED_SETTLEMENT = "S11_CARD_T2_SETTLEMENT"
    SPLIT_PAYMENT = "S04_SPLIT_PAYMENT"
    REFUND_REVERSAL = "S05_VALID_REVERSAL"
    DUPLICATE_CONTRADICTION = "S07_DUPLICATE_REVERSAL"
    AMBIGUOUS_CANDIDATE = "S14_CANDIDATE_TIE_AMBIGUITY"
    MISSING_RECORD = "S10_UNEXPLAINED_MISMATCH"
